import React, { useState, useEffect } from 'react';

const RandomTip = () => {
  // Define an array of tip objects, each containing multiple tips
  const tips = [
    {
      id: 1,
      tips: [
        "Align the curriculum more closely with industry standards based on feedback from employers.",
        "Ensure learning outcomes are clearly communicated to students at the beginning of each course.",
        "Introduce more interdisciplinary courses to foster a broader skill set.",
        "Incorporate more real-world case studies to enhance practical learning.",
        "Regularly update the syllabus to reflect current trends and innovations in the subject area.",
        "Include more opportunities for experiential learning in the curriculum.",
        "Increase the focus on problem-solving skills through project-based learning.",
        "Simplify complex topics into manageable learning modules to enhance comprehension.",
        "Build more opportunities for critical thinking within course assignments.",
        "Review course content periodically to eliminate outdated or redundant topics.",
        "Diversify curriculum content by incorporating global perspectives on issues.",
        "Align assignments with real-world scenarios to increase student engagement.",
        "Include ethics and sustainability topics in relevant courses.",
        "Provide opportunities for students to work on interdisciplinary projects.",
        "Integrate service learning into courses to increase student involvement in community projects.",
        "Ensure that each course addresses multiple learning styles, not just visual or auditory.",
        "Increase opportunities for hands-on learning in STEM programs.",
        "Introduce specialized elective courses for niche topics to allow deeper learning.",
        "Conduct curriculum mapping to ensure alignment with desired student outcomes.",
        "Include courses or modules that develop soft skills like communication and teamwork.",
        "Offer more flexible learning pathways to cater to students’ individual career goals.",
        "Ensure that the curriculum supports both theoretical knowledge and practical application.",
        "Regularly collect and analyze student feedback to make informed curriculum changes.",
        "Allow students to choose topics for certain assignments to foster creativity.",
        "Increase the focus on developing digital literacy skills across all courses.",
        "Include more group projects to teach collaboration and leadership.",
        "Regularly review the alignment of course outcomes with program outcomes.",
        "Introduce more project-based learning into courses that require practical skills.",
        "Regularly update readings and resources to reflect current research.",
        "Focus on reducing cognitive overload by breaking down complex topics.",
        "Offer more elective courses that align with emerging industries.",
        "Develop a course on learning how to learn to help students manage self-study better.",
        "Embed sustainability practices into the curriculum where relevant.",
        "Increase opportunities for research-based learning.",
        "Implement more blended learning models to combine online and in-person instruction.",
        "Encourage students to engage in cross-disciplinary research projects.",
        "Ensure course content supports innovation and entrepreneurship skills.",
        "Implement a modular approach to course design, allowing for flexibility in learning paths.",
        "Allow for personalized learning experiences through individual project-based courses.",
        "Develop opportunities for capstone projects in senior-level courses.",
        "Provide more opportunities for students to learn how to network in their industries.",
        "Ensure course learning outcomes are specific and measurable.",
        "Integrate continuous assessment in the curriculum to track progress.",
        "Introduce flipped classroom models to make class time more interactive.",
        "Incorporate collaborative technology like Slack or Trello into group projects.",
        "Offer more industry-validated certifications alongside traditional coursework.",
        "Promote research and innovation in final-year projects.",
        "Ensure regular input from industry experts during curriculum development.",
        "Focus on building resilience and adaptability through course design.",
        "Provide opportunities for students to develop emotional intelligence (EQ) in their coursework.",
        "Create specialized learning tracks for students pursuing advanced topics.",
        "Design more cross-cultural learning experiences.",
        "Encourage student-led seminars on advanced or specialized topics.",
        "Focus on integrating interdisciplinary knowledge into senior-level courses.",
        "Increase opportunities for internships or cooperative education placements.",
        "Regularly evaluate the relevance of textbook materials to ensure they meet current academic standards.",
        "Design courses that teach real-world problem-solving through simulations and case studies.",
        "Ensure learning outcomes are aligned with professional accreditation standards.",
        "Increase collaboration with other departments to create interdisciplinary courses.",
        "Implement more student-driven learning projects.",
        "Focus on building global competency through international collaboration projects.",
        "Increase emphasis on teaching digital literacy and cybersecurity in relevant courses.",
        "Regularly integrate student feedback to ensure curriculum improvements.",
        "Develop more personalized learning resources for students who need additional support.",
        "Increase courses focused on sustainable development and environmental impact.",
        "Integrate diversity, equity, and inclusion topics into the curriculum.",
        "Ensure the curriculum is designed with an eye on future career demands.",
        "Introduce micro-credentials for specific skills to increase employability.",
        "Offer courses that prepare students for certifications in their industry.",
        "Provide resources for self-paced learning alongside traditional lectures.",
        "Use interactive learning platforms to improve student engagement with difficult topics.",
        "Foster more industry collaboration in curriculum design.",
        "Update course content to include innovations like artificial intelligence and blockchain.",
        "Integrate entrepreneurial thinking into courses in all disciplines.",
        "Increase the inclusion of industry guest speakers to enhance learning.",
        "Develop more opportunities for collaborative international learning experiences.",
        "Create a curriculum review cycle where each course is reviewed every three years.",
        "Ensure the inclusion of ethical considerations in all courses.",
        "Encourage reflection and self-assessment in assignments.",
        "Develop interdisciplinary project-based learning courses.",
        "Include leadership training modules in senior-level courses.",
        "Improve career counseling support within courses.",
        "Expand the number of elective courses that offer hands-on learning experiences.",
        "Create virtual labs and simulations to enhance student learning in STEM fields.",
        "Encourage student participation in curriculum development through focus groups.",
        "Offer courses that are co-taught by industry experts and faculty members.",
        "Ensure regular curriculum alignment with accreditation bodies and industry standards.",
        "Develop courses that teach financial literacy and budgeting.",
        "Include more skill-based courses focused on practical knowledge in emerging fields.",
        "Focus on simplifying complex theories by using multimedia and interactive resources.",
        "Offer dual-degree or cross-institutional courses to broaden learning opportunities.",
        "Provide opportunities for students to lead seminars or workshops on specialized topics.",
        "Integrate lessons on workplace etiquette and professionalism into the curriculum.",
        "Ensure there is an emphasis on health, wellness, and personal development in the curriculum.",
        "Create case study competitions where students solve real-world industry problems.",
        "Review course prerequisites regularly to ensure they are still relevant.",
        "Increase collaboration between academic departments to create hybrid courses.",
        "Ensure courses provide opportunities for students to work on open-ended problems.",
        "Provide a mentoring program that aligns with curriculum goals.",
        "Align curriculum design with lifelong learning principles to ensure graduates continue learning after completing their degree."
    ]
    
    },
    {
      id: 2,
"tips": [
    "Increase focus on developing critical thinking skills in all courses.",
    "Create more opportunities for student presentations to enhance communication skills.",
    "Implement a tracking system to monitor students’ progress toward learning outcomes.",
    "Develop rubrics that clearly define how student outcomes are assessed.",
    "Encourage student self-assessment to help them take responsibility for their learning.",
    "Focus on developing emotional intelligence in students.",
    "Ensure students receive consistent feedback on their progress toward learning outcomes.",
    "Design activities that require students to apply theoretical knowledge to real-world situations.",
    "Offer more opportunities for students to engage in group problem-solving.",
    "Use assessment methods that test application, not just knowledge recall.",
    "Encourage students to develop portfolios that demonstrate their learning outcomes.",
    "Regularly revise assessment rubrics to ensure they reflect current learning goals.",
    "Provide opportunities for students to reflect on their learning and set goals for improvement.",
    "Introduce peer assessments to help students understand the importance of constructive feedback.",
    "Use student outcome data to inform continuous improvement of the curriculum.",
    "Create more opportunities for collaborative projects that span multiple courses.",
    "Offer a capstone course where students can demonstrate their accumulated learning outcomes.",
    "Use role-playing exercises to develop interpersonal and communication skills.",
    "Implement peer mentoring programs to foster collaboration between different year levels.",
    "Increase focus on research-based learning to develop problem-solving and critical thinking skills.",
    "Design courses to ensure alignment with industry and career-based student outcomes.",
    "Encourage active learning through group discussions, seminars, and debates.",
    "Ensure that course activities align directly with stated learning outcomes.",
    "Use technology to create simulations that demonstrate real-world outcomes.",
    "Ensure that learning outcomes are transparent and communicated at the beginning of every course.",
    "Offer more real-time feedback on assessments so students can track their progress.",
    "Encourage students to use digital tools to track their own progress.",
    "Focus on the development of leadership and teamwork skills in group projects.",
    "Increase emphasis on global citizenship as a student outcome.",
    "Use data-driven insights from student outcomes to modify teaching strategies.",
    "Offer training workshops that help students identify their learning styles and optimize their learning outcomes.",
    "Ensure that all courses align with program-level outcomes.",
    "Encourage cross-departmental collaborations to develop well-rounded students.",
    "Foster a growth mindset in students by emphasizing learning from failure.",
    "Develop more courses that focus on real-world problem-solving.",
    "Create benchmarks for student outcomes and track progress over time.",
    "Regularly compare student outcomes across different cohorts to identify trends.",
    "Encourage students to track their learning through portfolios or journals.",
    "Ensure that the focus on soft skills like empathy, collaboration, and adaptability is built into learning outcomes.",
    "Develop exit interviews or surveys to assess student outcomes after completing the course.",
    "Ensure that courses develop both technical skills and soft skills.",
    "Offer workshops or short courses focused on professional development and career readiness.",
    "Increase opportunities for students to work with industry professionals on real-world projects.",
    "Focus on building resilience and adaptability as part of learning outcomes.",
    "Create case studies where students can apply their learning in a practical context.",
    "Use data on student outcomes to improve advising and mentoring processes.",
    "Encourage students to reflect on how course content applies to their future careers.",
    "Increase focus on digital literacy and cybersecurity in all programs.",
    "Use assessments that require students to demonstrate their understanding of complex, real-world issues.",
    "Regularly evaluate how well students are meeting stated learning outcomes.",
    "Create opportunities for students to self-assess their progress at regular intervals.",
    "Offer more opportunities for peer-to-peer learning.",
    "Include outcomes that develop cultural competency and global awareness.",
    "Regularly evaluate assessments to ensure they measure intended outcomes.",
    "Focus on practical assessments that evaluate skills relevant to students' future careers.",
    "Design assignments that align directly with future career outcomes.",
    "Develop more opportunities for students to engage in research and innovation.",
    "Introduce more experiential learning outcomes through internships and cooperative education programs.",
    "Ensure that soft skills development is embedded in every course.",
    "Provide regular reports to students on their progress toward learning outcomes.",
    "Develop specific outcomes related to ethics and responsibility.",
    "Ensure there is a focus on social justice and equity in student outcomes.",
    "Include leadership development in the outcomes of senior-level courses.",
    "Encourage students to create a professional development plan based on learning outcomes.",
    "Regularly assess how well learning outcomes align with professional standards.",
    "Ensure students can demonstrate mastery of skills through projects and assessments.",
    "Create a system for tracking students' progress toward achieving program-level outcomes.",
    "Ensure students are prepared to work in culturally diverse environments.",
    "Offer more opportunities for self-directed learning outcomes.",
    "Regularly review assessments to ensure they measure critical thinking, problem-solving, and application.",
    "Develop interdisciplinary outcomes that integrate knowledge from multiple fields.",
    "Encourage students to focus on building innovation and creativity in their projects.",
    "Create more opportunities for students to practice public speaking and presentation skills.",
    "Ensure there are clear pathways for students to develop their career skills.",
    "Provide guidance to students on how to meet and exceed learning outcomes.",
    "Focus on building communication and conflict resolution skills through group activities.",
    "Offer more interdisciplinary research opportunities for students.",
    "Develop specific learning outcomes for technology-related skills.",
    "Encourage students to pursue internships that align with learning outcomes.",
    "Ensure that final-year projects demonstrate students’ mastery of course outcomes.",
    "Provide opportunities for students to engage with alumni for mentoring and feedback.",
    "Use project-based learning to ensure students can apply theoretical knowledge.",
    "Regularly assess whether learning outcomes are being met and make adjustments.",
    "Create opportunities for students to work on real-world case studies in their field.",
    "Focus on building emotional intelligence and interpersonal skills as part of learning outcomes.",
    "Regularly compare student outcomes against industry standards and expectations.",
    "Implement a feedback loop where students can evaluate how well their learning outcomes were met.",
    "Create opportunities for students to demonstrate leadership skills in group projects.",
    "Use problem-based learning to assess critical thinking and decision-making skills.",
    "Encourage students to participate in extracurricular activities that support learning outcomes.",
    "Focus on ensuring that learning outcomes are challenging but attainable.",
    "Provide continuous support and feedback to help students meet their outcomes.",
    "Create more opportunities for students to showcase their work to a broader audience.",
    "Encourage students to develop personal learning goals that align with course outcomes.",
    "Regularly review and refine student outcome rubrics to ensure they are aligned with current standards.",
    "Offer more experiential learning outcomes through collaboration with community organizations.",
    "Ensure learning outcomes are specific, measurable, achievable, relevant, and time-bound (SMART).",
    "Incorporate ethical considerations into learning outcomes.",
    "Provide support services for students struggling to meet outcomes.",
    "Regularly assess how well student outcomes are being communicated and understood."
],

    },
    {
      id: 3,
      tips: [
        "Incorporate active learning strategies to engage students.",
        "Use formative assessments throughout the course to adjust teaching methods.",
        "Implement flipped classroom models to increase student interaction during class time.",
        "Encourage peer learning by having students teach each other.",
        "Use storytelling as a method to make complex concepts more relatable.",
        "Increase the use of problem-based learning to encourage critical thinking.",
        "Focus on project-based learning to connect theory with practice.",
        "Use case studies to demonstrate the application of concepts in real-world situations.",
        "Incorporate more hands-on learning opportunities in the classroom.",
        "Use role-playing exercises to make abstract ideas more concrete.",
        "Create opportunities for collaborative learning to improve communication skills.",
        "Implement differentiated instruction to meet the diverse needs of students.",
        "Use interactive technology to enhance student engagement.",
        "Increase the use of simulations to provide practical learning experiences.",
        "Incorporate more group work to build teamwork and leadership skills.",
        "Use inquiry-based learning to encourage students to ask questions and seek answers.",
        "Incorporate metacognitive activities that encourage students to reflect on their learning.",
        "Use graphic organizers like mind maps to help students visualize complex ideas.",
        "Provide clear and consistent feedback on student work to promote improvement.",
        "Use collaborative learning platforms to encourage student interaction.",
        "Integrate experiential learning projects into courses to provide real-world applications.",
        "Regularly update teaching materials to reflect the latest research and trends.",
        "Focus on scaffolding lessons to gradually increase difficulty.",
        "Use digital storytelling tools to engage students in creative ways.",
        "Provide personalized learning opportunities based on student interests.",
        "Use rubrics to ensure fair and transparent grading.",
        "Increase the use of student presentations to build confidence and communication skills.",
        "Incorporate peer review activities to provide students with constructive feedback.",
        "Use think-pair-share techniques to promote student discussion and engagement.",
        "Focus on using open-ended questions to encourage deeper thinking.",
        "Create opportunities for cross-disciplinary learning to foster creativity.",
        "Use multimedia tools to cater to different learning styles.",
        "Incorporate reflective journaling to help students think about their learning process.",
        "Use real-time polling tools to check student understanding during lessons.",
        "Encourage students to take ownership of their learning through choice-based assignments.",
        "Use microteaching techniques to focus on specific skills or concepts.",
        "Increase the use of case-based learning to connect classroom content with real-world problems.",
        "Implement blended learning models to combine online and in-person instruction.",
        "Use collaborative annotation tools to engage students in discussions of readings.",
        "Incorporate more fieldwork or community-based projects into the curriculum.",
        "Use gamification to make learning more engaging and fun.",
        "Focus on creating inclusive classroom environments where all students feel valued.",
        "Use student feedback to adjust and improve teaching strategies.",
        "Incorporate self-assessment activities to help students monitor their own progress.",
        "Use breakout rooms in virtual environments to facilitate group discussions.",
        "Provide students with choices in how they demonstrate their learning.",
        "Focus on reducing lecture time to increase active learning opportunities.",
        "Use concept mapping tools to help students understand relationships between ideas.",
        "Incorporate digital tools like online quizzes and flashcards to reinforce learning.",
        "Focus on teaching students how to learn, not just what to learn.",
        "Implement teaching strategies that emphasize student engagement and participation.",
        "Provide more opportunities for students to engage in research-based learning.",
        "Use role-playing exercises to help students understand different perspectives.",
        "Increase opportunities for hands-on learning in science and technology courses.",
        "Focus on teaching students how to think critically and independently.",
        "Provide regular opportunities for students to reflect on their learning process.",
        "Use collaborative learning platforms to create interactive group assignments.",
        "Focus on creating opportunities for personalized learning experiences.",
        "Use data to track student progress and adjust teaching strategies accordingly.",
        "Implement peer mentoring programs to encourage collaboration between students.",
        "Encourage students to take ownership of their learning by setting personal goals.",
        "Use problem-based learning to encourage critical thinking and creativity.",
        "Incorporate active learning strategies like group discussions and debates.",
        "Increase opportunities for students to work on real-world projects in the classroom.",
        "Use flipped classroom models to encourage active participation in class.",
        "Focus on using inquiry-based learning to encourage student curiosity.",
        "Use formative assessments to provide regular feedback to students.",
        "Increase the use of project-based learning to help students apply what they’ve learned.",
        "Encourage students to think critically by asking open-ended questions.",
        "Use real-world case studies to help students understand the application of concepts.",
        "Focus on using collaborative learning strategies to build teamwork skills.",
        "Incorporate more hands-on learning opportunities in the classroom.",
        "Use technology to create interactive and engaging learning experiences.",
        "Increase opportunities for students to engage in peer review and feedback.",
        "Use graphic organizers like mind maps and concept maps to help students visualize ideas.",
        "Provide regular opportunities for students to reflect on their progress.",
        "Use student feedback to continually improve teaching methods.",
        "Increase opportunities for students to engage in research and experimentation.",
        "Focus on creating a collaborative learning environment in the classroom.",
        "Use project-based learning to help students develop problem-solving skills.",
        "Incorporate more experiential learning activities into courses.",
        "Use real-world problems to challenge students and develop critical thinking skills.",
        "Implement collaborative learning platforms to increase student engagement.",
        "Use flipped classroom models to create more time for active learning in class.",
        "Focus on using inquiry-based learning to encourage student curiosity.",
        "Use technology to create more interactive and engaging lessons.",
        "Increase opportunities for students to engage in peer review and feedback.",
        "Use formative assessments to provide regular feedback to students.",
        "Focus on using problem-based learning to develop critical thinking skills.",
        "Use project-based learning to connect theory with practice.",
        "Increase opportunities for students to work on interdisciplinary projects.",
        "Use storytelling to make abstract concepts more relatable and engaging.",
        "Implement digital learning tools to track student progress.",
        "Use real-world case studies to demonstrate the practical application of concepts.",
        "Focus on creating collaborative learning opportunities in group projects.",
        "Use reflective journaling to encourage students to think about their learning process.",
        "Incorporate peer learning opportunities into courses to build collaboration skills.",
        "Use simulations to create real-world learning experiences.",
        "Incorporate technology to enhance classroom engagement and learning outcomes.",
        "Use flipped classroom techniques to encourage more active learning during class time."
    ],
    
    }    
  ];

  // Function to get 8 random tips from an array
  const getRandomTips = (tipsArray, count) => {
    const shuffled = tipsArray.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
  };

  // State to store tips
  const [randomTips, setRandomTips] = useState([]);

  // Update tips on component mount
  useEffect(() => {
    const allRandomTips = tips.map(tipObject => getRandomTips(tipObject.tips, 3));
    setRandomTips(allRandomTips);
  }, []);

  return (
    <div className="container my-4">
      <div className="d-flex flex-wrap justify-content-center align-items-center px-4 w-100">
        <h3 style={{ color: "#4A4A4A", fontWeight: "bold", textAlign: "center", fontSize: "2rem" }}>
        Recommendations for further improvement
        </h3>
      </div>
      <div>
      {randomTips.map((tipsGroup, index) => (
            <div
              key={index}
              className="shadow-lg p-4 mb-4 rounded-4 bg-light"
              style={{
                borderLeft: "6px solid #ff004e",
                backgroundColor: "#ff004e",
              }}
            >
              <h5 style={{ fontWeight: "bold", color: "#333", marginBottom: "1rem" }}>
                <span style={{ color: "#ff004e" }}>Recommendation {tips[index].id}</span>{' '}
                {/* {Array.isArray(entry.programs) ? entry.programs.join(', ') : 'N/A'} */}
              </h5>
              <ul>
            {tipsGroup.map((tip, idx) => (
              <li key={idx}>{tip}</li>
            ))}
          </ul>
            </div>
          ))
      }
      </div>
    </div>

  );
};

export default RandomTip;